package com.flow.common.exception;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,
    INVALID_REQUEST,
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    ACCESS_DENIED
}
